apiVersion: v1
kind: Service
metadata:
  name: notes-app
spec:
  type: LoadBalancer
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
